version: '3.9'

services:
  SERVER_CENTRAL_SRV1:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: SERVER_CENTRAL_SRV1
    environment:
      - ORACLE_SID=centralSRV1
      - ORACLE_PDB=centralpdb
      - ORACLE_PWD=Central@2024SRV1
    ports:
      - "1521:1521"
    networks:
      - oracle_network
    volumes:
      - centralSRV1_data:/opt/oracle/oradata
      - ./init-tnsnames.sh:/docker-entrypoint-initdb.d/init-tnsnames.sh

  SERVER_CENTRAL_SRV2:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: SERVER_CENTRAL_SRV2
    environment:
      - ORACLE_SID=centralSRV2
      - ORACLE_PDB=centralpdb
      - ORACLE_PWD=Central@2024SRV2
    ports:
      - "1522:1521"
    networks:
      - oracle_network
    volumes:
      - centralSRV2_data:/opt/oracle/oradata
      - ./init-tnsnames.sh:/docker-entrypoint-initdb.d/init-tnsnames.sh

  SERVER_SC_SRV1:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: SERVER_SC_SRV1
    environment:
      - ORACLE_SID=scSRV1
      - ORACLE_PDB=scpdb
      - ORACLE_PWD=SanCarlos@2024SRV1
    ports:
      - "1523:1521"
    networks:
      - oracle_network
    volumes:
      - scSRV1_data:/opt/oracle/oradata
      - ./init-tnsnames.sh:/docker-entrypoint-initdb.d/init-tnsnames.sh

  SERVER_SC_SRV2:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: SERVER_SC_SRV2
    environment:
      - ORACLE_SID=scSRV2
      - ORACLE_PDB=scpdb
      - ORACLE_PWD=SanCarlos@2024SRV2
    ports:
      - "1524:1521"
    networks:
      - oracle_network
    volumes:
      - scSRV2_data:/opt/oracle/oradata
      - ./init-tnsnames.sh:/docker-entrypoint-initdb.d/init-tnsnames.sh

  SERVER_HR_SRV1:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: SERVER_HR_SRV1
    environment:
      - ORACLE_SID=hrSRV1
      - ORACLE_PDB=hrpdb
      - ORACLE_PWD=Heredia@2024SRV1
    ports:
      - "1525:1521"
    networks:
      - oracle_network
    volumes:
      - hrSRV1_data:/opt/oracle/oradata
      - ./init-tnsnames.sh:/docker-entrypoint-initdb.d/init-tnsnames.sh

  SERVER_HR_SRV2:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: SERVER_HR_SRV2
    environment:
      - ORACLE_SID=hrSRV2
      - ORACLE_PDB=hrpdb
      - ORACLE_PWD=Heredia@2024SRV2
    ports:
      - "1526:1521"
    networks:
      - oracle_network
    volumes:
      - hrSRV2_data:/opt/oracle/oradata
      - ./init-tnsnames.sh:/docker-entrypoint-initdb.d/init-tnsnames.sh

networks:
  oracle_network:
    driver: bridge

volumes:
  centralSRV1_data:
  centralSRV2_data:
  scSRV1_data:
  scSRV2_data:
  hrSRV1_data:
  hrSRV2_data:
