-- Tabla PERSONAS
CREATE TABLE PERSONAS (
    ID_PERSONA VARCHAR2(50) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    FEC_NACIMIENTO DATE,
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(20)
) TABLESPACE TBS_CENTRAL ;

--TRIGGERS
CREATE OR REPLACE TRIGGER trg_insert_personas
AFTER INSERT ON SC_CORE.PERSONAS
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.PERSONAS@SRV2_PLINK
  (ID_PERSONA, NOMBRE, APELLIDOS, FEC_NACIMIENTO, EMAIL, TELEFONO)
  VALUES
  (:NEW.ID_PERSONA, :NEW.NOMBRE, :NEW.APELLIDOS, :NEW.FEC_NACIMIENTO, :NEW.EMAIL, :NEW.TELEFONO);
END;

CREATE OR REPLACE TRIGGER trg_update_personas
AFTER UPDATE ON SC_CORE.PERSONAS
FOR EACH ROW
BEGIN
 
  UPDATE SC_CORE.PERSONAS@SRV2_PLINK
  SET NOMBRE = :NEW.NOMBRE,
      APELLIDOS = :NEW.APELLIDOS,
      FEC_NACIMIENTO = :NEW.FEC_NACIMIENTO,
      EMAIL = :NEW.EMAIL,
      TELEFONO = :NEW.TELEFONO
  WHERE ID_PERSONA = :NEW.ID_PERSONA;
END;