-- Tabla PROFESORES
CREATE TABLE PROFESORES (
    ID_PROFESOR NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPLEADO NUMBER ,
    ESPECIALIDAD VARCHAR2(100)
) TABLESPACE TBS_HEREDIA;


-- Tabla CARRERAS
CREATE TABLE CARRERAS (
    ID_CARRERA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255)
)  TABLESPACE TBS_HEREDIA;


-- Tabla ESTUDIANTES
CREATE TABLE ESTUDIANTES (
    ID_ESTUDIANTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PERSONA VARCHAR2(50) ,
    FEC_INGRESO DATE,
    ESTADO VARCHAR2(50)
) TABLESPACE TBS_HEREDIA;


-- Tabla CURSOS
CREATE TABLE CURSOS (
    ID_CURSO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CREDITOS NUMBER,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA)
)  TABLESPACE TBS_HEREDIA;


-- Tabla MATRICULA
CREATE TABLE MATRICULA (
    ID_MATRICULA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA_MATRICULA DATE,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA),
    ID_ESTUDIANTE NUMBER REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
    ID_SEDE NUMBER
)  TABLESPACE TBS_HEREDIA;


-- Tabla DETALLE_MATRICULA
CREATE TABLE DETALLE_MATRICULA (
    ID_DET_MATRICULA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MATRICULA NUMBER REFERENCES MATRICULA(ID_MATRICULA),
    ID_CURSO NUMBER REFERENCES CURSOS(ID_CURSO),
    ID_PROFESOR NUMBER REFERENCES PROFESORES(ID_PROFESOR)
)  TABLESPACE TBS_HEREDIA;


-- Tabla REGISTRO_NOTAS
CREATE TABLE REGISTRO_NOTAS (
    ID_REGISTRO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DET_MATRICULA NUMBER REFERENCES DETALLE_MATRICULA(ID_DET_MATRICULA),
    NOTA NUMBER,
    COMENTARIOS VARCHAR2(255)
)  TABLESPACE TBS_HEREDIA;