-- Crear un nuevo usuario
CREATE USER SC_CORE IDENTIFIED BY "C3ntR@12024Pw";

-- Otorgar permisos básicos al usuario
GRANT CONNECT, RESOURCE TO SC_CORE;

-- Otorgar permisos adicionales según sea necesario
GRANT CREATE SESSION TO SC_CORE;
GRANT CREATE TABLE TO SC_CORE;
GRANT CREATE VIEW TO SC_CORE;
GRANT CREATE PROCEDURE TO SC_CORE;





--DROP USER SC_CORE CASCADE;


DROP TABLE DETALLE_PAGARE;
DROP TABLE PAGARES;
DROP TABLE REGISTRO_NOTAS;
DROP TABLE DETALLE_MATRICULA;
DROP TABLE MATRICULA;
DROP TABLE CURSOS;
DROP TABLE CARRERAS;
DROP TABLE ESTUDIANTES;
DROP TABLE PROFESORES;
DROP TABLE EMPLEADOS;
DROP TABLE DEPARTAMENTO;
DROP TABLE SEDES;
DROP TABLE PERSONAS;



-- Crear un nuevo usuario
CREATE USER SSC_CORE IDENTIFIED BY "C3ntR@12024Pw";

-- Otorgar permisos básicos al usuario
GRANT CONNECT, RESOURCE TO SSC_CORE;

-- Otorgar permisos adicionales según sea necesario
GRANT CREATE SESSION TO SSC_CORE;
GRANT CREATE TABLE TO SSC_CORE;
GRANT CREATE VIEW TO SSC_CORE;
GRANT CREATE PROCEDURE TO SSC_CORE;


--CREAR TABLESPACE EN SYS
CREATE TABLESPACE TBS_SAN_CARLOS
DATAFILE '/opt/oracle/oradata/TBS_SAN_CARLOS.dbf' 
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED;

ALTER USER SSC_CORE QUOTA UNLIMITED ON TBS_SAN_CARLOS;