--CREAR TABLESPACE EN SYS
CREATE TABLESPACE TBS_CENTRAL
DATAFILE '/opt/oracle/oradata/TBS_CENTRAL.dbf' 
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED;

ALTER USER SC_CORE QUOTA UNLIMITED ON TBS_CENTRAL;

----
-- Tabla PERSONAS
CREATE TABLE PERSONAS (
    ID_PERSONA VARCHAR2(50) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    FEC_NACIMIENTO DATE,
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(20)
) TABLESPACE TBS_CENTRAL ;


-- Tabla SEDES
CREATE TABLE SEDES (
    ID_SEDE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_SEDE VARCHAR2(100) NOT NULL
) TABLESPACE TBS_CENTRAL;


-- Tabla DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SEDE NUMBER REFERENCES SEDES(ID_SEDE),
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255)
) TABLESPACE TBS_CENTRAL;


-- Tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PERSONA VARCHAR2(50) REFERENCES PERSONAS(ID_PERSONA),
    ID_DEPARTAMENTO NUMBER REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    SALARIO NUMBER,
    FEC_CONTRATACION DATE
) TABLESPACE TBS_CENTRAL;

-- Tabla PROFESORES
CREATE TABLE PROFESORES (
    ID_PROFESOR NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPLEADO NUMBER REFERENCES EMPLEADOS(ID_EMPLEADO),
    ESPECIALIDAD VARCHAR2(100)
) TABLESPACE TBS_CENTRAL;

-- Tabla ESTUDIANTES
CREATE TABLE ESTUDIANTES (
    ID_ESTUDIANTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PERSONA VARCHAR2(50) REFERENCES PERSONAS(ID_PERSONA),
    FEC_INGRESO DATE,
    ESTADO VARCHAR2(50)
) TABLESPACE TBS_CENTRAL;

-- Tabla CARRERAS
CREATE TABLE CARRERAS (
    ID_CARRERA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255)
)  TABLESPACE TBS_CENTRAL;

-- Tabla CURSOS
CREATE TABLE CURSOS (
    ID_CURSO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CREDITOS NUMBER,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA)
)  TABLESPACE TBS_CENTRAL;

-- Tabla MATRICULA
CREATE TABLE MATRICULA (
    ID_MATRICULA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA_MATRICULA DATE,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA),
    ID_ESTUDIANTE NUMBER REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
    ID_SEDE NUMBER REFERENCES SEDES(ID_SEDE)
)  TABLESPACE TBS_CENTRAL;

-- Tabla DETALLE_MATRICULA
CREATE TABLE DETALLE_MATRICULA (
    ID_DET_MATRICULA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MATRICULA NUMBER REFERENCES MATRICULA(ID_MATRICULA),
    ID_CURSO NUMBER REFERENCES CURSOS(ID_CURSO),
    ID_PROFESOR NUMBER REFERENCES PROFESORES(ID_PROFESOR)
)  TABLESPACE TBS_CENTRAL;

-- Tabla REGISTRO_NOTAS
CREATE TABLE REGISTRO_NOTAS (
    ID_REGISTRO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DET_MATRICULA NUMBER REFERENCES DETALLE_MATRICULA(ID_DET_MATRICULA),
    NOTA NUMBER,
    COMENTARIOS VARCHAR2(255)
)  TABLESPACE TBS_CENTRAL;

-- Tabla PAGARES
CREATE TABLE PAGARES (
    ID_PAGARE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPLEADO NUMBER REFERENCES EMPLEADOS(ID_EMPLEADO),
    MONTO NUMBER,
    FECHA_CONSTITUCION DATE,
    DESCRIPCION VARCHAR2(255)
)  TABLESPACE TBS_CENTRAL;

-- Tabla DETALLE_PAGARE
CREATE TABLE DETALLE_PAGARE (
    ID_DETALLE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PAGARE NUMBER REFERENCES PAGARES(ID_PAGARE),
    MONTO NUMBER,
    FECHA_PAGO DATE
)  TABLESPACE TBS_CENTRAL;
