--tabla profesores
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_PROFESORES" 
AFTER INSERT ON SC_CORE.PROFESORES
FOR EACH ROW
BEGIN

  INSERT INTO SC_CORE.PROFESORES@SRV2_PLINK
  (ID_PROFESOR, ID_EMPLEADO, ESPECIALIDAD)
  VALUES
  (:NEW.ID_PROFESOR, :NEW.ID_EMPLEADO, :NEW.ESPECIALIDAD);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_PROFESORES" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_PROFESORES" 
AFTER UPDATE ON SC_CORE.PROFESORES
FOR EACH ROW
BEGIN
  BEGIN

    UPDATE SC_CORE.PROFESORES@SRV2_PLINK
    SET ID_EMPLEADO = :NEW.ID_EMPLEADO,
        ESPECIALIDAD = :NEW.ESPECIALIDAD
    WHERE ID_PROFESOR = :NEW.ID_PROFESOR;
  EXCEPTION
    WHEN OTHERS THEN

      NULL; 
  END;
END;
/


--tabla carreras
 CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_CARRERAS" 
AFTER INSERT ON SC_CORE.CARRERAS
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.CARRERAS@SRV2_PLINK
  (ID_CARRERA, NOMBRE_CARRERA, DESCRIPCION)
  VALUES
  (:NEW.ID_CARRERA, :NEW.NOMBRE_CARRERA, :NEW.DESCRIPCION);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_CARRERAS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_CARRERAS" 
AFTER UPDATE ON SC_CORE.CARRERAS
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.CARRERAS@SRV2_PLINK
    SET NOMBRE_CARRERA = :NEW.NOMBRE_CARRERA,
        DESCRIPCION = :NEW.DESCRIPCION
    WHERE ID_CARRERA = :NEW.ID_CARRERA;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--tabla cursos
 CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_CURSOS" 
AFTER INSERT ON SC_CORE.CURSOS
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.CURSOS@SRV2_PLINK
  (ID_CURSO, NOMBRE, CREDITOS, ID_CARRERA)
  VALUES
  (:NEW.ID_CURSO, :NEW.NOMBRE, :NEW.CREDITOS, :NEW.ID_CARRERA);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_CURSOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_CURSOS" 
AFTER UPDATE ON SC_CORE.CURSOS
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.CURSOS@SRV2_PLINK
    SET NOMBRE = :NEW.NOMBRE,
        CREDITOS = :NEW.CREDITOS,
        ID_CARRERA = :NEW.ID_CARRERA
    WHERE ID_CURSO = :NEW.ID_CURSO;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--tabla departamentos
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_DEPARTAMENTO" 
AFTER INSERT ON SC_CORE.DEPARTAMENTO
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.DEPARTAMENTO@SRV2_PLINK
  (ID_DEPARTAMENTO, ID_SEDE, NOMBRE, DESCRIPCION)
  VALUES
  (:NEW.ID_DEPARTAMENTO, :NEW.ID_SEDE, :NEW.NOMBRE, :NEW.DESCRIPCION);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_DEPARTAMENTO" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_DEPARTAMENTO" 
AFTER UPDATE ON SC_CORE.DEPARTAMENTO
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.DEPARTAMENTO@SRV2_PLINK
    SET ID_SEDE = :NEW.ID_SEDE,
        NOMBRE = :NEW.NOMBRE,
        DESCRIPCION = :NEW.DESCRIPCION
    WHERE ID_DEPARTAMENTO = :NEW.ID_DEPARTAMENTO;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/


--detalle matricula
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_DETALLE_MATRICULA" 
AFTER INSERT ON SC_CORE.DETALLE_MATRICULA
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.DETALLE_MATRICULA@SRV2_PLINK
  (ID_DET_MATRICULA, ID_MATRICULA, ID_CURSO, ID_PROFESOR)
  VALUES
  (:NEW.ID_DET_MATRICULA, :NEW.ID_MATRICULA, :NEW.ID_CURSO, :NEW.ID_PROFESOR);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_DETALLE_MATRICULA" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_DETALLE_MATRICULA" 
AFTER UPDATE ON SC_CORE.DETALLE_MATRICULA
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.DETALLE_MATRICULA@SRV2_PLINK
    SET ID_MATRICULA = :NEW.ID_MATRICULA,
        ID_CURSO = :NEW.ID_CURSO,
        ID_PROFESOR = :NEW.ID_PROFESOR
    WHERE ID_DET_MATRICULA = :NEW.ID_DET_MATRICULA;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--detalle pagare
 CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_DETALLE_PAGARE" 
AFTER INSERT ON SC_CORE.DETALLE_PAGARE
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.DETALLE_PAGARE@SRV2_PLINK
  (ID_DETALLE, ID_PAGARE, MONTO, FECHA_PAGO)
  VALUES
  (:NEW.ID_DETALLE, :NEW.ID_PAGARE, :NEW.MONTO, :NEW.FECHA_PAGO);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_DETALLE_PAGARE" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_DETALLE_PAGARE" 
AFTER UPDATE ON SC_CORE.DETALLE_PAGARE
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.DETALLE_PAGARE@SRV2_PLINK
    SET ID_PAGARE = :NEW.ID_PAGARE,
        MONTO = :NEW.MONTO,
        FECHA_PAGO = :NEW.FECHA_PAGO
    WHERE ID_DETALLE = :NEW.ID_DETALLE;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--empleados:
 CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_EMPLEADOS" 
AFTER INSERT ON SC_CORE.EMPLEADOS
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.EMPLEADOS@SRV2_PLINK
  (ID_EMPLEADO, ID_PERSONA, ID_DEPARTAMENTO, SALARIO, FEC_CONTRATACION)
  VALUES
  (:NEW.ID_EMPLEADO, :NEW.ID_PERSONA, :NEW.ID_DEPARTAMENTO, :NEW.SALARIO, :NEW.FEC_CONTRATACION);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_EMPLEADOS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_EMPLEADOS" 
AFTER UPDATE ON SC_CORE.EMPLEADOS
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.EMPLEADOS@SRV2_PLINK
    SET ID_PERSONA = :NEW.ID_PERSONA,
        ID_DEPARTAMENTO = :NEW.ID_DEPARTAMENTO,
        SALARIO = :NEW.SALARIO,
        FEC_CONTRATACION = :NEW.FEC_CONTRATACION
    WHERE ID_EMPLEADO = :NEW.ID_EMPLEADO;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--estudiante:
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_ESTUDIANTES" 
AFTER INSERT ON SC_CORE.ESTUDIANTES
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.ESTUDIANTES@SRV2_PLINK
  (ID_ESTUDIANTE, ID_PERSONA, FEC_INGRESO, ESTADO)
  VALUES
  (:NEW.ID_ESTUDIANTE, :NEW.ID_PERSONA, :NEW.FEC_INGRESO, :NEW.ESTADO);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_ESTUDIANTES" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_ESTUDIANTES" 
AFTER UPDATE ON SC_CORE.ESTUDIANTES
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.ESTUDIANTES@SRV2_PLINK
    SET ID_PERSONA = :NEW.ID_PERSONA,
        FEC_INGRESO = :NEW.FEC_INGRESO,
        ESTADO = :NEW.ESTADO
    WHERE ID_ESTUDIANTE = :NEW.ID_ESTUDIANTE;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--matricula
 CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_MATRICULA" 
AFTER INSERT ON SC_CORE.MATRICULA
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.MATRICULA@SRV2_PLINK
  (ID_MATRICULA, FECHA_MATRICULA, ID_CARRERA, ID_ESTUDIANTE, ID_SEDE)
  VALUES
  (:NEW.ID_MATRICULA, :NEW.FECHA_MATRICULA, :NEW.ID_CARRERA, :NEW.ID_ESTUDIANTE, :NEW.ID_SEDE);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_MATRICULA" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_MATRICULA" 
AFTER UPDATE ON SC_CORE.MATRICULA
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.MATRICULA@SRV2_PLINK
    SET FECHA_MATRICULA = :NEW.FECHA_MATRICULA,
        ID_CARRERA = :NEW.ID_CARRERA,
        ID_ESTUDIANTE = :NEW.ID_ESTUDIANTE,
        ID_SEDE = :NEW.ID_SEDE
    WHERE ID_MATRICULA = :NEW.ID_MATRICULA;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--pagares
 CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_PAGARES" 
AFTER INSERT ON SC_CORE.PAGARES
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.PAGARES@SRV2_PLINK
  (ID_PAGARE, ID_EMPLEADO, MONTO, FECHA_CONSTITUCION, DESCRIPCION)
  VALUES
  (:NEW.ID_PAGARE, :NEW.ID_EMPLEADO, :NEW.MONTO, :NEW.FECHA_CONSTITUCION, :NEW.DESCRIPCION);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_PAGARES" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_PAGARES" 
AFTER UPDATE ON SC_CORE.PAGARES
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.PAGARES@SRV2_PLINK
    SET ID_EMPLEADO = :NEW.ID_EMPLEADO,
        MONTO = :NEW.MONTO,
        FECHA_CONSTITUCION = :NEW.FECHA_CONSTITUCION,
        DESCRIPCION = :NEW.DESCRIPCION
    WHERE ID_PAGARE = :NEW.ID_PAGARE;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/

--personas
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_PERSONAS" 
AFTER INSERT ON SC_CORE.PERSONAS
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.PERSONAS@SRV2_PLINK
  (ID_PERSONA, NOMBRE, APELLIDOS, FEC_NACIMIENTO, EMAIL, TELEFONO)
  VALUES
  (:NEW.ID_PERSONA, :NEW.NOMBRE, :NEW.APELLIDOS, :NEW.FEC_NACIMIENTO, :NEW.EMAIL, :NEW.TELEFONO);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_PERSONAS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_PERSONAS" 
AFTER UPDATE ON SC_CORE.PERSONAS
FOR EACH ROW
BEGIN

  UPDATE SC_CORE.PERSONAS@SRV2_PLINK
  SET NOMBRE = :NEW.NOMBRE,
      APELLIDOS = :NEW.APELLIDOS,
      FEC_NACIMIENTO = :NEW.FEC_NACIMIENTO,
      EMAIL = :NEW.EMAIL,
      TELEFONO = :NEW.TELEFONO
  WHERE ID_PERSONA = :NEW.ID_PERSONA;
END;
/

--REGISTRO NOTAS
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_REGISTRO_NOTAS" 
AFTER UPDATE ON SC_CORE.REGISTRO_NOTAS
FOR EACH ROW
BEGIN
  BEGIN

    UPDATE SC_CORE.REGISTRO_NOTAS@SRV2_PLINK
    SET ID_DET_MATRICULA = :NEW.ID_DET_MATRICULA,
        NOTA = :NEW.NOTA,
        COMENTARIOS = :NEW.COMENTARIOS
    WHERE ID_REGISTRO = :NEW.ID_REGISTRO;
  EXCEPTION
    WHEN OTHERS THEN

      NULL; 
  END;
END;
/
ALTER TRIGGER "SC_CORE"."TRG_UPDATE_REGISTRO_NOTAS" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_REGISTRO_NOTAS" 
AFTER INSERT ON SC_CORE.REGISTRO_NOTAS
FOR EACH ROW
BEGIN

  INSERT INTO SC_CORE.REGISTRO_NOTAS@SRV2_PLINK
  (ID_REGISTRO, ID_DET_MATRICULA, NOTA, COMENTARIOS)
  VALUES
  (:NEW.ID_REGISTRO, :NEW.ID_DET_MATRICULA, :NEW.NOTA, :NEW.COMENTARIOS);
END;
/

--SEDES
CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_INSERT_SEDES" 
AFTER INSERT ON SC_CORE.SEDES
FOR EACH ROW
BEGIN
  INSERT INTO SC_CORE.SEDES@SRV2_PLINK
  (ID_SEDE, NOMBRE_SEDE)
  VALUES
  (:NEW.ID_SEDE, :NEW.NOMBRE_SEDE);
END;
/
ALTER TRIGGER "SC_CORE"."TRG_INSERT_SEDES" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SC_CORE"."TRG_UPDATE_SEDES" 
AFTER UPDATE ON SC_CORE.SEDES
FOR EACH ROW
BEGIN
  BEGIN
    UPDATE SC_CORE.SEDES@SRV2_PLINK
    SET NOMBRE_SEDE = :NEW.NOMBRE_SEDE
    WHERE ID_SEDE = :NEW.ID_SEDE;
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;
END;
/